{
 "title": "Dashboard Pacientes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "PatientID",
    "label": "Patient ID",
    "query": "SELECT \"patient-id\" FROM \"blood-oxygen\""
   }
  ]
 },
 "panels": [
  { "title": "Oxígeno en sangre", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Oxigeno en sangre SpO2 - Paciente: ${PatientID}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blood-oxygen",
     "query": "SELECT \"value\" FROM \"blood-oxygen\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Oxígeno en sangre actual - Paciente: ${PatientID}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SpO2" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"blood-oxygen\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alertas por nivel bajo de oxígeno - Paciente: ${PatientID}",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SpO2" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"meassured-value\" as \"Valor de la alarma\" FROM \"alarm\"  WHERE \"patient-id\" = '${PatientID}'  AND \"type\" = 'blood-oxygen' ORDER BY DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Ritmo cardiaco", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pulsaciones por minuto - Paciente: ${PatientID}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blood-oxygen",
     "query": "SELECT \"value\" FROM \"heartbeat\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pulsaciones por minuto actual - Paciente: ${PatientID}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"heartbeat\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alertas por pulso peligroso - Paciente: ${PatientID}",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "SpO2" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"meassured-value\" as \"Valor de la alarma\" FROM \"alarm\"  WHERE \"patient-id\" = '${PatientID}'  AND \"type\" = 'heartbeat' ORDER BY DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Temperatura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Temperatura - Paciente: ${PatientID}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blood-oxygen",
     "query": "SELECT \"value\" FROM \"temperature\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatura actual - Paciente: ${PatientID}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "SpO2" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"temperature\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alertas por temperatura peligrosa - Paciente: ${PatientID}",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "SpO2" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"meassured-value\" as \"Valor de la alarma\" FROM \"alarm\"  WHERE \"patient-id\" = '${PatientID}'  AND \"type\" = 'temperature' ORDER BY DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}